# Generated by Django 4.2.9 on 2024-01-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bako_mili", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Role", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
            ],
        ),
    ]
