# Generated by Django 4.2.9 on 2024-01-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bako_mili", "0002_officer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="officer",
            old_name="Role",
            new_name="role",
        ),
    ]
