# Generated by Django 4.2.9 on 2024-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bako_mili", "0003_rename_role_officer_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="revenue",
            name="paid_from",
        ),
        migrations.AddField(
            model_name="revenue",
            name="collector",
            field=models.CharField(default="Bs", max_length=50),
        ),
    ]
