# Generated by Django 4.2.9 on 2024-01-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bako_mili", "0004_remove_revenue_paid_from_revenue_collector"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revenue",
            old_name="customer",
            new_name="Payer",
        ),
    ]
