# Generated by Django 4.2.9 on 2024-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bako_mili", "0007_expense_alter_revenue_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="expense_bill_pics"
            ),
        ),
    ]
